# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PartitioningRankingLevel <- function(y, sigma, crit, n, trace) {
    .Call(`_ICRanks_PartitioningRankingLevel`, y, sigma, crit, n, trace)
}

PartitioningRankingBlockCorrectOrder <- function(y, sigma, crit, MinBlock, MaxBlock, Lower, Upper, n, trace) {
    .Call(`_ICRanks_PartitioningRankingBlockCorrectOrder`, y, sigma, crit, MinBlock, MaxBlock, Lower, Upper, n, trace)
}

